site_name: RESTful Resource Mapping Language
site_url: http://localhost:8000

theme:
  name: material
  font:
    code: Red Hat Mono
  logo: assets/images/rrms_v3.png
  favicon: assets/images/rrms_logo.png
  palette:
    primary: blue grey
    accent: orange
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.sections

extra_css:
  - assets/css/custom.css

# Enable MkDocs plugins
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            merge_init_into_class: true

# Where your markdown pages live
docs_dir: docs
site_dir: site      # build output goes to ./site (temporary)

# Pages shown in the left navigation
nav:
  - Overview: index.md
  - Model:
    - Definition of Resources: ResourceMain.md
    - Definition of mapping Resources to Database: ResourceToDbMain.md
  - YAML Examples: Examples.md

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details